### ISSUE TITLE
Class Monero_rpc not found.

### ISSUE THREAD

**Issue by apezio** [monero-integrations/monerowhmcs#3]
library.php was missing so I copied it from https://github.com/monero-integrations/monerowp/tree/master/monero

Not sure if that's the same file, but it worked.

Now createinvoice.php is complaining:

Fatal error: Class 'Monero_rpc' not found in /full/path/modules/gateways/monero/createinvoice.php on line 15

**Comment by serhack** [comment]
Oh, you are right! The library, I will commit it asap! Thanks for remember me
