### ISSUE TITLE
Links broken when WHMCS in sub directory

### ISSUE THREAD

**Issue by Jayd603** [monero-integrations/monerowhmcs#40]
I run WHMCS in a /billing sub directory.   This breaks a few links within the code.  Simply adding a "system url path" variable before the links resolves it.

Also, there is an additional "/" in the link to createinvoice.php , simply removing it cleans up the url display (it still works without this fix obv).

Other than that I just tested this code as working on the latest WHMCS.

Two questions, is there a timeout on the invoice display at all?   ...and how does this set up handle multiple people trying to pay at once?  Is there no conflicts when 4-5 people try to pay an invoice at once for example?

Anyway, thanks a lot for writing this code!

**Comment by apezio** [comment]
There is no timeout.

There's no problem with multiple payments at once, each is in it's own session and is seperated from the others.

If you could make a pull request with the changes that would be helpful.  I looked but can't find the issues you mentioned.
